export const OTHER_INDUSTRY_VALUE = 'Other';

export const INDUSTRY_OPTIONS = [
  {
    value: 'Cleaning Services',
    label:
      'Cleaning Services (weekly/biweekly home cleaning, move-in/out, deep cleans, office/retail/medical/commercial post-construction)',
  },
  {
    value: 'Plumbing',
    label: 'Plumbing (residential/commercial repairs, installations, emergencies)',
  },
  {
    value: 'HVAC / Heating & Cooling',
    label: 'HVAC / Heating & Cooling (installs, maintenance, repairs)',
  },
  {
    value: 'Landscaping & Lawn Care',
    label: 'Landscaping & Lawn Care (mowing, trimming, irrigation, seasonal cleanups)',
  },
  {
    value: 'Handyman / General Maintenance',
    label: 'Handyman / General Maintenance (repairs, assembly, small projects)',
  },
  {
    value: 'Pest Control',
    label: 'Pest Control (extermination, prevention, inspections)',
  },
  {
    value: 'Pool & Spa Maintenance',
    label: 'Pool & Spa Maintenance (cleaning, chemical balancing, repairs)',
  },
  {
    value: 'Pressure Washing / Exterior Cleaning',
    label: 'Pressure Washing / Exterior Cleaning (driveways, roofs, siding)',
  },
  {
    value: 'Window Cleaning',
    label: 'Window Cleaning (residential, commercial, high-rise)',
  },
  {
    value: 'Carpet & Upholstery Cleaning',
    label: 'Carpet & Upholstery Cleaning (steam cleaning, stain removal)',
  },
  {
    value: 'Delivery & Courier Services',
    label: 'Delivery & Courier Services (food, packages, medical, local)',
  },
  {
    value: 'Pet Sitting / Dog Walking',
    label: 'Pet Sitting / Dog Walking (recurring visits, boarding)',
  },
  {
    value: 'Mobile Detailing / Car Wash',
    label: 'Mobile Detailing / Car Wash (auto detailing at home/office)',
  },
  {
    value: 'Home Organizing / Decluttering',
    label: 'Home Organizing / Decluttering (professional organizers)',
  },
  {
    value: 'Tutoring / Education Services',
    label: 'Tutoring / Education Services (in-home or online recurring)',
  },
  {
    value: 'Massage Therapy / Wellness',
    label: 'Massage Therapy / Wellness (in-home or mobile sessions)',
  },
  {
    value: 'Internet / Information Technology',
    label: 'Internet / Information Technology (managed IT, cybersecurity, hosting, networking)',
  },
  {
    value: 'Web Development / Design',
    label: 'Web Development / Design (websites, apps, UX/UI, ecommerce)',
  },
  {
    value: 'Graphic Design',
    label: 'Graphic Design (logos, branding, marketing collateral)',
  },
  {
    value: 'Insurance',
    label: 'Insurance (commercial, personal, risk management, claims support)',
  },
  {
    value: OTHER_INDUSTRY_VALUE,
    label: 'Other / Custom (free-text fallback for anything else)',
  },
] as const;

export const INDUSTRY_KEYWORDS: Record<string, string[]> = {
  'Cleaning Services': [
    'weekly cleaning',
    'maid service',
    'house cleaner needed',
    'deep clean',
    'move out cleaning',
    'office cleaning',
    'commercial janitorial',
    'post construction cleaning',
    'recurring cleaning',
    'pressure washing driveway',
  ],
  Plumbing: [
    'plumber needed',
    'emergency plumber',
    'leak repair',
    'water heater install',
    'pipe burst',
    'plumbing repair',
  ],
  'HVAC / Heating & Cooling': [
    'HVAC technician',
    'air conditioning repair',
    'furnace service',
    'heater maintenance',
    'cooling system repair',
    'mini split service',
  ],
  'Landscaping & Lawn Care': [
    'lawn mowing',
    'landscape design',
    'irrigation repair',
    'seasonal clean-up',
    'yard maintenance',
    'tree trimming',
  ],
  'Handyman / General Maintenance': [
    'handyman needed',
    'home repairs',
    'assembly service',
    'small renovation',
    'odd jobs',
    'general maintenance',
  ],
  'Pest Control': [
    'pest control service',
    'termite inspection',
    'exterminator',
    'rodent removal',
    'bed bug treatment',
    'mosquito treatment',
  ],
  'Pool & Spa Maintenance': [
    'pool maintenance',
    'spa cleaning',
    'pool chemical balancing',
    'pool equipment repair',
    'pool opening service',
    'spa maintenance',
  ],
  'Pressure Washing / Exterior Cleaning': [
    'pressure washing driveway',
    'roof cleaning',
    'siding pressure wash',
    'gutter cleaning',
    'exterior cleaning',
    'deck washing',
  ],
  'Window Cleaning': [
    'window washing',
    'high rise window cleaning',
    'residential window cleaner',
    'commercial window service',
    'skyscraper window washing',
    'window washing service',
  ],
  'Carpet & Upholstery Cleaning': [
    'carpet cleaning',
    'upholstery cleaning',
    'steam carpet cleaning',
    'stain removal',
    'rug cleaning',
    'deep carpet cleaning',
  ],
  'Delivery & Courier Services': [
    'delivery driver',
    'courier service',
    'package delivery',
    'medical courier',
    'same day delivery',
    'last mile delivery',
  ],
  'Pet Sitting / Dog Walking': [
    'dog walker',
    'pet sitter',
    'pet boarding',
    'pet care visit',
    'in home pet sitting',
    'dog walking service',
  ],
  'Mobile Detailing / Car Wash': [
    'mobile detailing',
    'car wash at home',
    'auto detailing service',
    'vehicle ceramic coating',
    'mobile car detailer',
    'on-site detailing',
  ],
  'Home Organizing / Decluttering': [
    'professional organizer',
    'decluttering service',
    'garage cleanout',
    'closet organizer',
    'home staging tidy',
    'organizing appointment',
  ],
  'Tutoring / Education Services': [
    'tutor needed',
    'math tutor',
    'online tutoring',
    'homework help',
    'STEM tutor',
    'education services',
  ],
  'Massage Therapy / Wellness': [
    'mobile massage',
    'massage therapist',
    'wellness session',
    'in-home massage',
    'corporate chair massage',
    'spa massage',
  ],
  'Internet / Information Technology': [
    'managed IT',
    'network support',
    'cybersecurity service',
    'cloud hosting',
    'IT consultant',
    'infrastructure support',
  ],
  'Web Development / Design': [
    'web design',
    'custom website',
    'ecommerce development',
    'UX/UI designer',
    'front end developer',
    'web development',
  ],
  Insurance: [
    'insurance agent',
    'insurance broker',
    'commercial insurance',
    'insurance quote',
    'risk management',
    'insurance review',
  ],
  [OTHER_INDUSTRY_VALUE]: ['freelance', 'gig', 'contract', 'service business', 'small business'],
};
